apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.redhat.io/rhscl/mongodb-36-rhel7
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_USER
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_PASSWORD
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_DATABASE
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
  triggers:
  - type: ConfigChange
